version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"              # Location of requirements.txt
    schedule:
      interval: "weekly"        # Checks for updates once a week
      day: "monday"
      time: "08:00"
    groups:
      security-updates:
        applies-to: security-updates
      regular-updates:
        applies-to: version-updates
    ignore:
      - dependency-name: "discord.py"
        versions: ["<2.0.0"]    # Ignore outdated major versions
    commit-message:
      prefix: "deps:"
      include: "scope"
